server:
  port: 8081
  forward-headers-strategy: framework
  use-forward-headers: true


logging:
  level:
    root: info

vaadin:
  launch-browser: true
  allowed-packages: 
    - com.vaadin
    - org.vaadin
    - com
  productionMode: false
  frontend:
    hotdeploy: true